---
# tasks file for sa-hashicorp-vault
  - include: tasks_nginx.yml
    when: option_install_nginx

  - include: tasks_vault.yml

  - include: vault_console_tools.yml
    when: option_install_console_tools
