---
# tasks file for sa-hashicorp-vault

  - include_tasks: use/__detect_init_system.yml

  - include_tasks: tasks_nginx.yml
    when: option_install_nginx

  - include_tasks: tasks_vault.yml

  - include_tasks: vault_console_tools.yml
    when: option_install_console_tools

  - include_tasks: tasks_vault_bootstrap_storage.yml
    when: option_bootstrap_storage and vault_bootstrap_file_storage is defined
