---

  - name: Vault | Check if is present
    command: test -x {{vault_path}}/vault
    ignore_errors: yes
    register: vault_present
    tags:
      - vault

  - name: Vault | Dependencies
    apt: pkg="{{item}}" state="present"
    with_items:
      - curl
      - unzip
    when: vault_present | failed
    tags:
      - vault

  - name: Vault | Create installation directory
    file: dest="{{vault_path}}" mode=755 state=directory
    become: yes
    tags:
      - vault

  - debug: msg="Downloading https://releases.hashicorp.com/vault/{{vault_version}}/vault_{{vault_version}}_linux_amd64.zip"
    tags:
      - vault

  - name: Vault | Download
    get_url: url="https://releases.hashicorp.com/vault/{{vault_version}}/vault_{{vault_version}}_linux_amd64.zip" dest="/tmp/vault.zip" validate_certs="no"
    when: vault_present | failed
    tags:
      - vault

  - name: Vault | Install
    unarchive: src=/tmp/vault.zip dest="{{vault_path}}" copy=no
    become: yes
    when: vault_present | failed
    tags:
      - vault

  - name: Vault | Template config
    template: src="{{role_dir}}/templates/vault/vault-config.hcl.j2" dest="{{vault_path}}/vault-config.hcl"
    become: yes
    when: vault_present | failed
    tags:
      - vault

  - name: Vault | Template vault-server
    template: src="{{role_dir}}/templates/vault/vault-server.j2" dest="{{vault_path}}/vault-server" mode="0755"
    become: yes
    when: vault_present | failed
    tags:
      - vault

  - name: Vault | Template upstart script
    template: src="{{role_dir}}/templates/vault/vault-upstart.conf.j2" dest="/etc/init/vault-server.conf"
    become: yes
    when: upstart_system=="upstart" and vault_present | failed
    tags:
      - vault

  - name: Vault | Create systemd service
    template: src={{role_dir}}/templates/vault/vault.service.j2 dest=/etc/systemd/system/vault-server.service mode=0644
    when: upstart_system=="systemd" and vault_present | failed
    become: yes
    tags:
      - vault


  - name: Vault | Start service
    service: name="vault-server" state="restarted" enabled="yes"
    become: yes
    when: docker_test is not defined and vault_present | failed
    tags:
      - vault

  - name: Vault | Template nginx template
    template: src="{{role_dir}}/templates/vault/nginx.conf.j2" dest="/etc/nginx/sites-available/vault.conf"
    when: option_install_nginx
    become: yes
    tags:
      - vault

  - name: Vault | Enable sites
    command: ln -fs /etc/nginx/sites-available/vault.conf /etc/nginx/sites-enabled/vault creates=/etc/nginx/sites-enabled/vault
    become: yes
    tags:
      - vault

  - name: Vault | Check if certificate is present
    command: test -x {{vault_ssl_certificate_path}}/{{vault_ssl_certificate}}.crt
    ignore_errors: yes
    register: vault_cert_present
    become: yes
    tags:
      - vault

  - name: Vault | Check if dhparam is present
    command: test -x {{vault_ssl_certificate_path}}/dhparam.pem
    ignore_errors: yes
    register: vault_dhparam_present
    become: yes
    tags:
      - vault

  - name:  Vault | NGINX - Generate self signed certs
    include: use/__create_selfsigned_cert.yml key="{{vault_ssl_certificate_key}}" crt="{{vault_ssl_certificate}}" fqdn="{{vault_domain}}" target_dir="{{vault_ssl_certificate_path}}"
    when: option_install_nginx and option_self_signed_cert and vault_cert_present|failed
    tags:
      - vault

  - name: Vault | Copy predefined dhparam for prod deploy debugging purposes
    copy: "src={{role_dir}}/files/nginx/dhparam.pem dest={{vault_ssl_certificate_path}}/dhparam.pem"
    sudo: yes
    when: option_predefined_dhparam and vault_dhparam_present | failed
    tags:
      - vault

  - name: Client | Generate nginx dhparam.pem if not exists
    command: openssl dhparam -out {{vault_ssl_certificate_path}}/dhparam.pem {{ssl_dhparam_size}} creates={{vault_ssl_certificate_path}}/dhparam.pem
    when: vault_dhparam_present | failed
    become: yes
    tags:
      - vault

  - name: Vault | restart nginx
    service: name="nginx" state="restarted"
    when: docker_test is not defined
    become: yes
    tags:
      - vault
