---
  - name: Vault | Stop Vault server
    service: name="vault-server" state="stopped"
    become: yes
    tags:
      - vault

  - name: Vault | Unpack storage to bootstrapped
    unarchive: src="" dest="" owner="root" group="root"
    become: yes
    tags:
      - vault

