---
- hosts: www
  gather_facts: False

  vars:
    - root_dir: ..
    - my_vault_domain: vvault.voronenko.net
    - my_domains:
      - {
          names:        "{{my_vault_domain}}",
#          nginx_config: "/etc/nginx/sites-available/letsencrypt_site_to_validate"
        }

  pre_tasks:
    - debug: msg="Pre tasks section"

    - name: ANSIBLE PYTHON | install python 2
      raw: test -e /usr/bin/python || (apt -qqy update && apt install -qy python-minimal)
      become: yes

    - name:  UNPRIVILEGED USERS | Get acl dependency (ansible unprivileged user operations magic)
      apt: pkg="acl"
      become: yes

    - name: gather facts
      setup:

  roles:

     - {
         role: "sa-nginx"  
       }

     - {
          role:              "sa-dehydrated",
          le_domains:        "{{ my_domains }}",
#          le_ca:            "https://acme-staging-v02.api.letsencrypt.org/directory",
          option_run_once:   True,
          option_setup_cron: True
       }

     - {
         role: "sa-hashicorp-vault",
         vault_version: 0.11.1,
         option_self_signed_cert: false,
         vault_ssl_certificate_path: "/opt/letsencrypt/certs/{{my_vault_domain}}",
         vault_ssl_certificate: "fullchain.pem",
         vault_ssl_certificate_key: "privkey.pem"
#         option_bootstrap_storage: true,
#         vault_bootstrap_storage_file: "/home/slavko/softasap/ansible/sa-hashicorp-vault/box-example/vault.tar.gz"
       }


  tasks:
    - debug: msg="Tasks section"
