---
- hosts: www

  vars:
    - root_dir: ..
    - my_vault_domain: vvault.voronenko.net
    - my_domains:
      - {
          names:        "{{my_vault_domain}}",
          nginx_config: "/etc/nginx/sites-available/letsencrypt_site_to_validate"
        }

  pre_tasks:
    - debug: msg="Pre tasks section"

  roles:

     - {
          role:              "sa-nginx",
       }


     - {
          role:              "sa-dehydrated",
          le_domains:        "{{ my_domains }}",
          le_ca:            "https://acme-staging.api.letsencrypt.org/directory",
          option_run_once:   True,
          option_setup_cron: True
       }

     - {
         role: "sa-hashicorp-vault",
         vault_version: 0.9.0,
         option_self_signed_cert: true
#         option_bootstrap_storage: true,
#         vault_bootstrap_storage_file: "/home/slavko/softasap/ansible/sa-hashicorp-vault/box-example/vault.tar.gz"
       }


  tasks:
    - debug: msg="Tasks section"
