#!/bin/bash -e
###
### Script to restore Jenkins data generated by jenkins backup script
###
### NOTE:
###   - Requires passwordless sudo
###   - Works on Debian/Ubuntu
###
###

### Display usage

VAULT_HOME=/opt/vault



### EOF
